formatter: "markdown table"

content: |-
  ## Examples

  ### slackingway-bot

  ```hcl
  {{ include "example/slackingway_bot.tf" }}
  ```

  ### dreamingway-bot

  ```hcl
  {{ include "example/dreamingway_bot.tf" }}
  ```

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
